<?php
$env = parse_ini_file('.env');

$ENV_MYSQL_HOST = $env["MYSQL_HOST"];
$ENV_MYSQL_USER = $env['MYSQL_USER'];
$ENV_MYSQL_PASSWORD = $env['MYSQL_PASSWORD'];
$ENV_MYSQL_DATABASE = $env['MYSQL_DATABASE'];

$ENV_MONGO_HOST = $env["MONGO_HOST"];
$ENV_MONGO_USER = $env['MONGO_USER'];
$ENV_MONGO_PASSWORD = $env['MONGO_PASSWORD'];

?>
