<?php
$pathx = explode('/', $path);
array_pop($pathx);
$pathx = implode('/', $pathx); 
$env = parse_ini_file("$pathx/.env");

$ENV_MYSQL_HOST = $env["MYSQL_HOST"];
$ENV_MYSQL_USER = $env['MYSQL_USER'];
$ENV_MYSQL_PASSWORD = $env['MYSQL_PASSWORD'];
$ENV_MYSQL_DATABASE = $env['MYSQL_DATABASE'];

$ENV_MONGO_HOST = $env["MONGO_HOST"];
$ENV_MONGO_USER = $env['MONGO_USER'];
$ENV_MONGO_PASSWORD = $env['MONGO_PASSWORD'];

$ENV_ZOHO_CRM_REFRESH_TOKEN = $env["ZOHO_CRM_REFRESH_TOKEN"];
$ENV_ZOHO_CRM_CLIENT_ID = $env['ZOHO_CRM_CLIENT_ID'];
$ENV_ZOHO_CRM_CLIENT_SECRET = $env['ZOHO_CRM_CLIENT_SECRET'];

$ENV_ZOHO_PROJECTS_REFRESH_TOKEN = $env["ZOHO_PROJECTS_REFRESH_TOKEN"];
$ENV_ZOHO_PROJECTS_CLIENT_ID = $env['ZOHO_PROJECTS_CLIENT_ID'];
$ENV_ZOHO_PROJECTS_CLIENT_SECRET = $env['ZOHO_PROJECTS_CLIENT_SECRET'];
$ENV_ZOHO_PROJECTS_PORTAL_ID = $env['ZOHO_PROJECTS_PORTAL_ID'];

$ENV_ZOHO_ANALYTICS_REFRESH_TOKEN = $env["ZOHO_ANALYTICS_REFRESH_TOKEN"];
$ENV_ZOHO_ANALYTICS_CLIENT_ID = $env['ZOHO_ANALYTICS_CLIENT_ID'];
$ENV_ZOHO_ANALYTICS_CLIENT_SECRET = $env['ZOHO_ANALYTICS_CLIENT_SECRET'];

$ENV_INTELISIS_MSSQL_IP = $env["INTELISIS_MSSQL_IP"];
$ENV_INTELISIS_MSSQL_PORT = $env["INTELISIS_MSSQL_PORT"];
$ENV_INTELISIS_MSSQL_INSTANCE = $env["INTELISIS_MSSQL_INSTANCE"];
$ENV_INTELISIS_MSSQL_USER = $env["INTELISIS_MSSQL_USER"];
$ENV_INTELISIS_MSSQL_PASSWORD = $env["INTELISIS_MSSQL_PASSWORD"];
$ENV_INTELISIS_MSSQL_DATABASE = $env["INTELISIS_MSSQL_DATABASE"];




?>
